[project]
name = "ebird-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=2.18.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "geopy"
]
